; Local 1% config for a medium-size input stream.

[DEFAULT]
DataFilePath = .
WindowSize = 60000
ScaleFactor = 0.01

isLineitem = yes
isOrders = yes
isCustomer = yes
isPartSupp = yes
isPart = yes
isSupplier = yes
isNation = yes
isRegion = yes

OutputFileName = input_data_1pct_insert_only.csv

[KAFKA_CONF]
KafkaEnable = no
BootstrapServer = localhost:9092
KafkaTopic = aju_data_generator
